### ISSUE TITLE
What is the advantages of Objax over pytorch ? (Take RepVGG for example)

### ISSUE THREAD

**Issue by sisrfeng** [benjaminjellis/Objax-RepVGG#1]

**Comment by benjaminjellis** [comment]
Hi,

From a personal perspective: Objax gives you the advantages of JAX (JITing etc.) in a PyTorch style OO package. So if you want to use JAX but you don't want to  get too functional Objax is great. 

I also like authors [philosophy](https://objax.readthedocs.io/en/latest/index.html#objax-philosophy) of simple, easy to extend code that is high performance. 

Like anything though, I think it ultimately comes down to personal preference!

I hope that answers your question,
Thanks :)

**Comment by sisrfeng** [comment]
Thx!
Is your code faster than author's on GPU ? Would you mind sharing more information on speed test ?

**Comment by benjaminjellis** [comment]
Hi, 

I haven't done any speed tests so I'm not sure if the Objax models would be faster than the original PyTorch ones.
